# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the v2.8 branch
  push:
    branches: [ v2.8 ]
  pull_request:
    branches: [ v2.8 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6
        
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.100.1
        with:
          ruby-version: 2.7.2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '8'
          
      - name: Install sass
        run: gem install sass

      - name: Restore NuGet packages
        run: nuget restore src\Merchello.sln

      - name: Install NPM packages
        working-directory: src\Merchello.Web.UI.Client
        run: npm install -g grunt-cli
        
      - name: Dump version
        working-directory: src\Merchello.Web.UI.Client
        run: |
          npm -v
          node -v
          ruby -v
          sass -v
          grunt -version

      - name: Install NPM packages for Merchello.Web.UI.Client
        working-directory: src\Merchello.Web.UI.Client
        run: npm install

      - name: Grunt build for Merchello.Web.UI.Client
        working-directory: src\Merchello.Web.UI.Client
        run: grunt build

      - name: Install NPM packages for Merchello.Providers.UI.Client
        working-directory: src\Merchello.Providers.UI.Client
        run: npm install

      - name: Grunt build for Merchello.Providers.UI.Client
        working-directory: src\Merchello.Providers.UI.Client
        run: grunt build

      - name: Install NPM packages for Merchello.Mui.Client
        working-directory: src\Merchello.Mui.Client
        run: npm install

      - name: Grunt build for Merchello.Mui.Client
        working-directory: src\Merchello.Mui.Client
        run: grunt build
        
      - name: Build the Solution
        run: msbuild build\package.proj
        env:
          APPVEYOR_BUILD_VERSION: 2.8.0

      - uses: actions/upload-artifact@v3
        with:
          name: Merchello.Core
          path: artifacts\Merchello.Core.*.nupkg

      - uses: actions/upload-artifact@v3
        with:
          name: Merchello.FastTrack
          path: artifacts\Merchello.FastTrack.*.nupkg
          
      - name: publish Merchello.Core package
        run:  dotnet.exe nuget push artifacts\Merchello.Core.*.nupkg --source github --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
          
      - name: publish Merchello.FastTrack package
        run:  dotnet.exe nuget push artifacts\Merchello.FastTrack.*.nupkg --source github --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
    
